In [5]:
import numpy as np

## What is an array?

In programming, arrays are data structures built on a sequencial way in the RAM memory of the machine. For doing this sequencial allocation, arrays must contain data with the same type, which is different from the lists where you can store different data types in a single list.

Here, we gonna build arrays with the numpy module, building a numpy array object that can allow us to use attributes and a lot of methods (functions).

In [1]:
# Trying to multiplie the values of a list by 2
grades = [1, 2, 3, 4]
grades * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [4]:
list(map(lambda grade : grade * 2, grades))

[2, 4, 6, 8]

## Building Matrices

Each list passed as argument for the ``array`` function from np module is a line of the matrix.

For 1D:

In [7]:
matrix_1d = np.array([1, 2, 3, 4])
matrix_1d

array([1, 2, 3, 4])

For 2D:

In [8]:
matrix_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
# Multiplying each element of grades by 2 | much more simple
grades_np = np.array(grades)
print(grades_np)
print(grades_np * 2)

[1 2 3 4]
[2 4 6 8]


## Math Operations

Numpy arrays works like vectors (Physics and Math). So, the math operations are made as in Math, like the sum of two vectors reults on a new vector with elements as the result of the sum of the two positional corresponding elements of the other two vectors.

**Element Wise Operations**

In [12]:
vector_1 = np.array([1, 2, 3])
vector_2 = np.array([4, 5, 6])
print(vector_1 + vector_2)
print(vector_1 * vector_2)

[5 7 9]
[ 4 10 18]


## Matrices Shape or Dimensions

We can discover the shape of a matrice using the ``shape`` attribute, which returns a tuple like ``(rows, columns)``, or discover the dimension of the matrix using the ``ndim`` function.

In [17]:
print(matrix_1d.shape)
print(matrix_1d.ndim)
print(matrix_2d.shape)
print(matrix_2d.ndim)

(4,)
1
(3, 4)
2


## Matrix Multiplication

The multiplication among matrices is done with the ``dot`` function, respecting the rules of the dimensions for doing the multiplication.

## Broadcasting

Check the broadcasting article by USP: https://panda.ime.usp.br/algoritmos/static/algoritmos/03-adt3-arrays.html#operacoes-entre-arrays-de-tamanhos-distintos

### Pratice

Supose a certain 2D matrix A, we want to rotate A which is the point (3, 4) on the 2d plan XY by 180°. We can do it multiplying A by D, being D:

$$D = \begin{bmatrix}-1 & 0 \\ 0 & -1\end{bmatrix}$$

We can see that the shapes of the matrices are: $A_{1x2}$ and $D_{2x2}$. So, the matrix product among A and D results on a new rotated matrix $R_{1x2}$

In [21]:
A = np.array([3, 4])
D = np.array([[-1, 0], [0, -1]])
rotated_point = np.dot(A, D)
rotated_point

array([-3, -4])

## Data types

Check out for more data types of arrays: http://www.estruturas.ufpr.br/disciplinas/pos-graduacao/introducao-a-computacao-cientifica-com-python/introducao-python/2-3-arrays-mais-elaborados/

## Arrange and Linspace

In [22]:
print(np.arange(5))
print(np.arange(0, 2, 0.4))
print(np.linspace(0, 2, 5))

[0 1 2 3 4]
[0.  0.4 0.8 1.2 1.6]
[0.  0.5 1.  1.5 2. ]
